### ISSUE TITLE
XPI compilation for FF 88.0

### ISSUE THREAD

**Issue by harl** [dvalter/ff-thegreatsuspender#1]
Hi.
Would it seem reasonable to you, if you provided a pre-compiled / pre-packed xpi file for this?

Without having much experience in compiling stuff, and having to install different additional libraries, compilers etc for every other uncompiled software, I feel that it is way too complicated for every single user to have to compile it, compared to compiling it once and making it available from a distinct location.  I'm not even sure how to properly install and use most of these things.

And would this version of TGS even work with the latest FF versions?

**Comment by dvalter** [comment]
Sorry for the almost 3 years late response.
I provide a pre-packed "pure" XPI as well as an XPI signed by Mozilla in assets for each release.
